[workspace]
members = [
    "dpu/dpu-runtime-manager",
    "host/examples/attestation",
    "host/examples/provision_execute",
    "host/examples/parsec_execute",
]

resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
